version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samex1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rkf0wqticttf"
s3_prefix = "samex1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
